openapi: 3.0.0
info:
  title: Musikverein 1914 Münster e. V.
  version: '1.0'
  description: ''
  contact:
    name: Simon Neidig
    email: simon.neidig@mvm1914.de
  license:
    name: MIT
servers:
  - url: 'https://mvm1914.de'
paths:
  /wp-json/jwt-auth/v1/token:
    post:
      summary: Create JSON-Web-Token
      operationId: post-wp-json-jwt-auth-v1-token
      responses:
        '200':
          description: 'The user will receive this message, if the login was successful.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user_email:
                    type: string
                  user_nicname:
                    type: string
                  user_display_name:
                    type: string
              examples:
                Example:
                  value:
                    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvbXZtMTkxNC5kZSIsImlhdCI6MTU4NDIwODUxMiwibmJmIjoxNTg0MjA4NTEyLCJleHAiOjE1ODQ4MTMzMTIsImRhdGEiOnsidXNlciI6eyJpZCI6IjEifX19.VozRX-5xI76hHV29AYFvsisX1YXaT4W-pjWuI9APA6Q
                    user_email: simon@neidig-web.de
                    user_nicename: sneidig
                    user_display_name: Simon Neidig
        '403':
          description: 'This message will be returned, if the password does not match to the username or one field is missing.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invalid-Creadentials'
              examples:
                Example - wrong password:
                  value:
                    code: '[jwt_auth] incorrect_password'
                    message: '<strong>FEHLER</strong>: Das Passwort, das du für den Benutzernamen <strong>SNeidig</strong> eingegeben hast, ist nicht korrekt. <a href="https://mvm1914.de/wp-login.php?action=lostpassword">Passwort vergessen?</a>'
                    data:
                      status: 403
                Example - missing field:
                  value:
                    code: '[jwt_auth] empty_password'
                    message: '<strong>FEHLER</strong>: Das Passwortfeld ist leer.'
                    data:
                      status: 403
      tags:
        - Authorization
      description: This route is for generating a JSON Web Token by given username and password.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
        description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: 'Content-Type: application/json'
  /wp-json/jwt-auth/v1/token/validate:
    post:
      summary: Validate JSON-Web-Token
      operationId: post-wp-json-jwt-auth-v1-token-validate
      responses:
        '200':
          description: 'The user will receive a status-code 200, if the given JWT is valid.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  data:
                    type: object
                    properties:
                      status:
                        type: integer
              examples:
                Example:
                  value:
                    code: jwt_auth_valid_token
                    data:
                      status: 200
        '403':
          description: 'The user receives a status-code 403, if the given JWT is invalid.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: jwt_auth_invalid_token
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      status:
                        type: number
                        description: '403'
              examples:
                Example:
                  value:
                    code: jwt_auth_invalid_token
                    message: Signature verification failed
                    data:
                      status: 403
      tags:
        - Authorization
      description: This route allows a validation of the JWT.
      security:
        - JSON Web Token: []
  /wp-json/mvm/v1/post:
    get:
      summary: Retrieve Information about all Articles
      tags:
        - Post
      responses:
        '200':
          description: 'If the request was successful, the user will receive an array of all articles in an shortened form.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./post.v1.yaml
              examples:
                Example: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Example:
                  value:
                    error: {}
        '':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./post.v1.yaml
          description: A response to a successful request consits of an array of all shortened information about articles of the homepage.
      operationId: get-wp-json-mvm-v1-post
      description: ''
  '/wp-json/mvm/v1/post/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Retrieve Information about a specific Article
      tags:
        - Post
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./post_extended.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Example:
                  value:
                    error: {}
      operationId: get-wp-json-mvm-v1-post-id
  '/wp-json/mvm/v1/event/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Retrieve Information about a specific Event
      tags:
        - Event
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./event_extended.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Example:
                  value:
                    error: {}
      operationId: get-wp-json-mvm-event-id
  /wp-json/mvm/v1/event:
    get:
      summary: Retrieve Information about all Events
      tags:
        - Event
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./event.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Example:
                  value:
                    error: {}
      operationId: get-wp-json-mvm-v1-event
  /wp-json/mvm/v1/gallery:
    get:
      summary: Retrieve Information about all Galleries
      tags:
        - Gallery
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    year:
                      type: integer
                    galleries:
                      type: array
                      items:
                        $ref: ./gallery.v1.yaml
              examples: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Example:
                  value:
                    error: {}
      operationId: get-wp-json-mvm-v1-gallery
  '/wp-json/mvm/v1/gallery/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Retrieve Information about a specific Gallery
      tags:
        - Gallery
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./gallery_extended.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Example:
                  value:
                    error: {}
      operationId: get-wp-json-mvm-v1-gallery-id
  /wp-json/mvm/v1/contact:
    get:
      summary: Request for Contactpersons
      tags:
        - Contact
      responses:
        '200':
          description: The response to a successful response delivers all contactpersons of the club.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./contact.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Example:
                  value:
                    error: {}
      operationId: get-wp-json-mvm-v1-contact
  /wp-json/mvm/v1/group:
    get:
      summary: Retrieve all Groups of the Club
      tags:
        - Group
      responses:
        '200':
          description: If the request was successful the user will receive an array of all groups in the club.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./group.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Example:
                  value:
                    error: {}
      operationId: get-wp-json-mvm-v1-group
components:
  schemas:
    Invalid-Creadentials:
      title: Invalid-Creadentials
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        data:
          type: object
          properties:
            status:
              type: integer
      x-examples:
        Example - Invalid Password:
          code: '[jwt_auth] incorrect_password'
          message: '<strong>FEHLER</strong>: Das Passwort, das du für den Benutzernamen <strong>SNeidig</strong> eingegeben hast, ist nicht korrekt. <a href="https://mvm1914.de/wp-login.php?action=lostpassword">Passwort vergessen?</a>'
          data:
            status: 403
        Example - Missing Field:
          code: '[jwt_auth] empty_password'
          message: '<strong>FEHLER</strong>: Das Passwortfeld ist leer.'
          data:
            status: 403
  securitySchemes:
    JSON Web Token:
      type: http
      scheme: Bearer
